[package]
name = "sdrglue"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.18", features = ["derive"] }
rustfft = "6.2.0"
soapysdr = { version = "0.4.0", path = "../rust-soapysdr" }
wide = "0.7.28"
